### PR TITLE
allow approver to complete manual merge activities

### PR DESCRIPTION
**Pull request by tdashworth**
## Purpose
On our project, the user approving the Solution Merge will often also carry out the manual steps (documented in a Note). The problem is that only the creator of the Solution Merge Request can confirm these have been done via an Approval.

#81

## Approach
Allows both creator and approver to complete the manual merge activities. 

image

## TODOs
- [x] Automated test coverage for new code
- [x] Documentation updated (if required)
- [x] Build and tests successful

### CODE REVIEW

**Comment by tdashworth** [comment]
Closes #81.

**Review by ewingjm — DISMISSED** [review]

**Comment by tdashworth** [comment]
@ewingjm Thanks for reviewing. I think you need to manually trigger the checks?

**Comment by ewingjm** [comment]
@tdashworth would you mind adding this into the power-apps-bindings.yml?

```yaml
browserOptions:
  driversPath: ChromeWebDriver
```

Should fix the error you're getting on the pipeline. I was going to just bypass the policy and merge this as I know it doesn't impact the few tests that are there but I realised we'll just get the same error on the CI run and we won't get a release published.

**Review by ewingjm — APPROVED** [review]
Thanks @tdashworth.

**Pull request merged**
